#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: learningcenter-delegation
  namespace: learningcenter
spec:
  delegations:
    - secretName: #@ "learning-center-{}".format(data.values.ingress.contour_tls_secret)
      targetNamespaces:
        - "*"