apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterSupplyChain/source-test-scan-to-url;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"ClusterSupplyChain","metadata":{"labels":{"kapp.k14s.io/app":"1643386193380751418","kapp.k14s.io/association":"v1.8c64ddca205b2ba4c71428ca92333680"},"name":"source-test-scan-to-url"},"spec":{"params":[{"default":"main","name":"gitops_branch"},{"default":"supplychain","name":"gitops_user_name"},{"default":"supplychain","name":"gitops_user_email"},{"default":"supplychain@cluster.local","name":"gitops_commit_message"},{"default":"","name":"gitops_ssh_secret"}],"resources":[{"name":"source-provider","params":[{"name":"serviceAccount","value":"default"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"source-template"}},{"name":"deliverable","params":[{"name":"registry","value":{"repository":"apps","server":"harbor.apps.cf.tanzutime.com"}}],"templateRef":{"kind":"ClusterTemplate","name":"deliverable-template"}},{"name":"source-tester","sources":[{"name":"source","resource":"source-provider"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"testing-pipeline"}},{"name":"source-scanner","sources":[{"name":"source","resource":"source-tester"}],"templateRef":{"kind":"ClusterSourceTemplate","name":"source-scanner-template"}},{"name":"image-builder","params":[{"name":"serviceAccount","value":"default"},{"name":"clusterBuilder","value":"default"},{"name":"registry","value":{"repository":"apps","server":"harbor.apps.cf.tanzutime.com"}}],"sources":[{"name":"source","resource":"source-scanner"}],"templateRef":{"kind":"ClusterImageTemplate","name":"kpack-template"}},{"images":[{"name":"image","resource":"image-builder"}],"name":"image-scanner","templateRef":{"kind":"ClusterImageTemplate","name":"image-scanner-template"}},{"images":[{"name":"image","resource":"image-scanner"}],"name":"config-provider","params":[{"name":"serviceAccount","value":"default"}],"templateRef":{"kind":"ClusterConfigTemplate","name":"convention-template"}},{"configs":[{"name":"config","resource":"config-provider"}],"name":"app-config","templateRef":{"kind":"ClusterConfigTemplate","name":"config-template"}},{"configs":[{"name":"config","resource":"app-config"}],"name":"config-writer","params":[{"name":"serviceAccount","value":"default"},{"name":"registry","value":{"repository":"apps","server":"harbor.apps.cf.tanzutime.com"}}],"templateRef":{"kind":"ClusterTemplate","name":"config-writer-template"}}],"selector":{"apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
  creationTimestamp: "2022-01-28T16:09:53Z"
  generation: 1
  labels:
    kapp.k14s.io/app: "1643386193380751418"
    kapp.k14s.io/association: v1.8c64ddca205b2ba4c71428ca92333680
  name: source-test-scan-to-url
  resourceVersion: "1256318"
  uid: a3862f2d-1d0b-4127-adc9-b4e8bd6cda31
spec:
  params:
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: ""
    name: gitops_ssh_secret
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: deliverable
    params:
    - name: registry
      value:
        repository: apps
        server: harbor.apps.cf.tanzutime.com
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  - name: source-tester
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: testing-pipeline
  - name: source-scanner
    sources:
    - name: source
      resource: source-tester
    templateRef:
      kind: ClusterSourceTemplate
      name: source-scanner-template
  - name: image-builder
    params:
    - name: serviceAccount
      value: default
    - name: clusterBuilder
      value: default
    - name: registry
      value:
        repository: apps
        server: harbor.apps.cf.tanzutime.com
    sources:
    - name: source
      resource: source-scanner
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-template
  - images:
    - name: image
      resource: image-builder
    name: image-scanner
    templateRef:
      kind: ClusterImageTemplate
      name: image-scanner-template
  - images:
    - name: image
      resource: image-scanner
    name: config-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: config-template
  - configs:
    - name: config
      resource: app-config
    name: config-writer
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        repository: apps
        server: harbor.apps.cf.tanzutime.com
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  selector:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
status:
  conditions:
  - lastTransitionTime: "2022-01-28T16:09:53Z"
    message: ""
    reason: Ready
    status: "True"
    type: TemplatesReady
  - lastTransitionTime: "2022-01-28T16:09:53Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  observedGeneration: 1
